
name: "bilstm_word"

data:
    src: "zh"
    trg: "yue"
    train: "/yue_nmt/bitext_mining/data/bitext_and_ud/split/train"
    dev: "/yue_nmt/bitext_mining/data/bitext_and_ud/split/valid"
    test:  "/yue_nmt/bitext_mining/data/bitext_and_ud/split/test"
    level: "word" 
    lowercase: False
    max_sent_length: 160
    src_voc_min_freq: 1
    trg_voc_min_freq: 1
   
testing:
    beam_size: 10
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.0003
    learning_rate_min: 0.0000005
    batch_size: 64
    scheduling: "noam"
    patience: 5 
    learning_rate_factor: 0.5
    learning_rate_warmup: 1000
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 100
    validation_freq: 200
    logging_freq: 200
    eval_metric: "bleu"
    model_dir: "/yue_nmt/models/bilstm_word"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 150
    print_valid_sents: [0, 1, 2, 3]

model:
    encoder:
        rnn_type: "lstm"
        embeddings: 
            embedding_dim: 128
            scale: False 
        hidden_size: 256
        bidirectional: True
        dropout: 0.25
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 128
            scale: False
        emb_scale: False
        hidden_size: 256
        dropout: 0.25
        hidden_dropout: 0.3
        num_layers: 1
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"


